# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run app.py on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up virtual display with Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        # Start Xvfb in the background (it simulates a graphical display)
        Xvfb :99 -screen 0 1280x1024x24 &
        # Export DISPLAY variable for the current session
        export DISPLAY=:99
        echo "DISPLAY is set to: $DISPLAY"  # To verify that DISPLAY is set

    - name: Run app.py
      env:
        DISPLAY: ":99"  # Ensure DISPLAY is available to the Python script
      run: |
        echo "Running app.py with DISPLAY set to: $DISPLAY"
        python app.py

